version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - restore_cache:
          keys:
          - 76faf0d2-cbb5-40b3-9fb7-e93da50360b2
      - run: cat file.txt
