version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - restore_cache:
          keys:
          - c7981447-68b6-46dd-95f6-8ca4f825e224
      - run: cat file.txt
