version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - restore_cache:
          keys:
          - the-key2 
      - run: cat file.txt
