version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - checkout
      - run: echo "content" >> file.txt
      - save_cache:
          key: "the-key2"
          paths:
            - ./file.txt
      - restore_cache:
          keys:
          - the-key2
      - run: cat file.txt
