version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - restore_cache:
          keys:
          - 428b2b42-a1b4-4bf8-bfaf-e7570939b6e3
      - run: cat file.txt
