version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - restore_cache:
          keys:
          - 6d260edd-8d3e-4070-9a1a-4f9f22c56e07
      - run: cat file.txt
