version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - checkout
      - run: echo "AND FORWARDS AGAIN" >> file.txt
      - save_cache:
          key: "the-key"
          paths:
            - ./file.txt
