version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    macos:
      xcode: "12.2"
    resource_class: metal
    steps:
      - checkout
      - run: echo "domtent" >> file.txt
      - save_cache:
          key: "the-key2"
          paths:
            - ./file.txt
      - restore_cache:
          keys:
          - the-key2
      - run: cat file.txt
