version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    macos:
      xcode: "12.2"
    resource_class: metal
    steps:
      - checkout
      - run: echo "this is not the greatest PR in the world, this is just a tribute"
      - run: echo "content2" >> file.txt
      - save_cache:
          key: "the-key"
          paths:
            - ./file.txt