version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    machine:
      resource_class: medium
    steps:
      - run: echo "This is from kcciperm" > file.txt
      - save_cache:
          key: 428b2b42-a1b4-4bf8-bfaf-e7570939b6e3
          paths:
          - file.txt
