version: 2.1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "Hmmm"
      - run: echo "content" >> file.txt
      - save_cache:
          key: "the-key"
          paths:
            - ./file.txt
